services:
  postgres:
    image: postgres:17
    container_name: express-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express_app

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: express-api
    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/express_app
      NODE_ENV: production

    ports:
      - "3000:3000"

volumes:
  postgres_data:
    name: backend-practice_postgres_data
